#!/usr/bin/env python3
"""Apply videos/motionova-timing.json to both Motionova projects (16:9 and 9:16).

Rewrites, idempotently:
  - index.html  : the frame hosts between <!-- FRAMES:BEGIN --> / <!-- FRAMES:END -->,
                  the VO <audio id="vo"> start/duration and the music ducking lane.
  - compositions/transitions.html : wipe clips + wipe() calls between WIPES markers.
  - compositions/frames/<id>.html : the `const CUES = {...}` block between
                  // CUES:BEGIN and // CUES:END (scene-local seconds) and the
                  data-duration of every data-start="0" clip (= scene length).
Usage: python3 tools/retime.py [--check] [--only <scene-id>]
  --only: touch only that scene's two frame files (safe while other scenes are being edited).
"""
import json, re, sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
TIMING = json.loads((ROOT / "motionova-timing.json").read_text())
PROJECTS = [("motionova-promo", 1920, 1080), ("motionova-promo-9x16", 1080, 1920)]
CHECK = "--check" in sys.argv
ONLY = sys.argv[sys.argv.index("--only") + 1] if "--only" in sys.argv else None
changed = []


def write(path, text):
    old = path.read_text()
    if old != text:
        changed.append(str(path.relative_to(ROOT)))
        if not CHECK:
            path.write_text(text)


def r(x):
    return float(f"{x:.3f}")


def between(text, begin, end, body, path):
    pat = re.compile(re.escape(begin) + r".*?" + re.escape(end), re.S)
    if not pat.search(text):
        sys.exit(f"markers {begin} / {end} missing in {path}")
    return pat.sub(lambda _m: begin + body + end, text, count=1)


for proj, w, h in PROJECTS:
    pdir = ROOT / proj
    if ONLY:
        for sc in TIMING["scenes"]:
            if sc["id"] == ONLY:
                break
        else:
            sys.exit(f"unknown scene {ONLY}")
    # --- index.html
    idx = pdir / "index.html"
    s = idx.read_text()
    hosts = "\n"
    for i, sc in enumerate(TIMING["scenes"], 1):
        dur = r(sc["end"] - sc["start"])
        hosts += (f'      <div id="f{i:02d}" class="clip frame" data-composition-id="{sc["id"]}" '
                  f'data-composition-src="compositions/frames/{sc["id"]}.html" data-start="{r(sc["start"])}" '
                  f'data-duration="{dur}" data-track-index="1" data-width="{w}" data-height="{h}"></div>\n')
    hosts += "      "
    s = between(s, "<!-- FRAMES:BEGIN -->", "<!-- FRAMES:END -->", hosts, idx)
    vo = TIMING["vo"]
    s = re.sub(r'(<audio\s+id="vo"[^>]*?data-start=")[^"]*(")', lambda m: m.group(1) + str(r(vo["start"])) + m.group(2), s, flags=re.S)
    s = re.sub(r'(<audio\s+id="vo"[^>]*?data-duration=")[^"]*(")', lambda m: m.group(1) + str(r(vo["duration"])) + m.group(2), s, flags=re.S)
    end = vo["end"]
    lane = {"version": 1, "lanes": [{"target": "volume", "points": [
        {"t": 0, "v": 0.3}, {"t": 0.25, "v": 0.2}, {"t": r(end - 0.4), "v": 0.2}, {"t": r(end + 0.2), "v": 0.48},
        {"t": 28.3, "v": 0.48}, {"t": 29.95, "v": 0}]}]}
    s = re.sub(r"(<audio\s+id=\"music\".*?data-automation=')[^']*(')", lambda m: m.group(1) + json.dumps(lane, separators=(",", ":")) + m.group(2), s, flags=re.S)
    if not ONLY:
        write(idx, s)

    # --- transitions.html
    tr = pdir / "compositions" / "transitions.html"
    t = tr.read_text()
    clips = "\n"
    calls = "\n"
    for wp in TIMING["wipes"]:
        a, b = ("wipe-pink", "wipe-navy") if wp["panel"] == "pink" else ("wipe-navy", "wipe-pink")
        clips += (f'      <div id="{wp["id"]}" class="wipe clip" data-start="{r(wp["cut"] - 0.3)}" data-duration="0.7" data-track-index="0">\n'
                  f'        <div id="{wp["id"]}-panel" data-layout-allow-overflow class="wipe-panel {a}"></div>\n'
                  f'        <div id="{wp["id"]}-trail" data-layout-allow-overflow class="wipe-trail {b}"></div>\n'
                  f'      </div>\n')
        calls += f'      wipe("{wp["id"]}", {r(wp["cut"])}, {wp["dir"]});\n'
    clips += "      "
    calls += "      "
    t = between(t, "<!-- WIPES:BEGIN -->", "<!-- WIPES:END -->", clips, tr)
    t = between(t, "// WIPES:BEGIN", "// WIPES:END", calls, tr)
    if not ONLY:
        write(tr, t)

    # --- frames
    for sc in TIMING["scenes"]:
        if ONLY and sc["id"] != ONLY:
            continue
        fp = pdir / "compositions" / "frames" / f'{sc["id"]}.html'
        if not fp.exists():
            print(f"skip (missing): {fp.relative_to(ROOT)}")
            continue
        f = fp.read_text()
        if "// CUES:BEGIN" not in f:
            print(f"skip (no CUES markers yet): {fp.relative_to(ROOT)}")
            continue
        dur = r(sc["end"] - sc["start"])
        local = {k: r(v - sc["start"]) for k, v in sc["cues"].items()}
        body = "\n      const CUES = " + json.dumps(local, ensure_ascii=False) + "; // scene-local seconds, generated by tools/retime.py\n      const DUR = " + str(dur) + ";\n      "
        f = between(f, "// CUES:BEGIN", "// CUES:END", body, fp)
        f = re.sub(r'(data-start="0" data-duration=")[0-9.]+(")', lambda m: m.group(1) + str(dur) + m.group(2), f)
        write(fp, f)

print(("would change" if CHECK else "changed") + ":", changed or "nothing")
